spring:
  sharding:
    datasources:
      ds0:
        url: jdbc:mysql://localhost:3306/db0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin_88!
      ds1:
        url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin_88!
    tables:
      t_user:
        actualDataNodes: db0.t_user0, db0.t_user1, db0.t_user2, db1.t_user0, db1.t_user1, db1.t_user2
        databaseStrategy:
          type: hash
          shardingColumn: id
          algorithmExpression: db${id % 2}
        tableStrategy:
          type: hash
          shardingColumn: id
          algorithmExpression: t_user${id % 3}